# Site settings
title: FrontendLabs PRE
email: pre@frontendlabs.io
description: > # this means to ignore newlines until "baseurl:"
  Testing with jekyll and docker :D
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pre.frontendlabs.io" # the base hostname & protocol for your site
twitter_username: frontendlabs
github_username: frontendlabs

# Build settings
markdown: kramdown
